test for library implementation of persistence service implemented persistence service command and SMF service cactl changes to interact with stash service

diff --git a/smf/method/canodesvc b/smf/method/canodesvc
--- a/smf/method/canodesvc
+++ b/smf/method/canodesvc
@@ -101,6 +101,14 @@ ns_node="$(getprop caconfig/path-node)"
 ns_logbase="$(getprop caconfig/path-logs)"
 ns_rt=$(getprop caconfig/run-rt)
 ns_name=
+ns_args=
+
+#
+# Set up log files and directories
+#
+mkdir -p "$ns_logbase/$ns_name" || fail "failed to create log directory"
+ns_dbglogfile="$ns_logbase/$ns_name/amqp-$(date +%F.%T).$$"
+ns_rqlogfile="$ns_logbase/$ns_name/requests-$(date +%F.%T).$$"
 
 #
 # Figure out which service to start.
@@ -108,13 +116,22 @@ ns_name=
 case $SMF_FMRI in
 	*caconfigsvc*)	ns_name=caconfigsvc
 			load_mapi
+			ns_args="$ns_dbglogfile $ns_rqlogfile"
 			;;
 	*caaggsvc*)	export HOST=$(uname -n)-${SMF_FMRI/*:}
 			ns_name=caaggsvc
 			load_geoip
+			ns_args="$ns_dbglogfile"
 			;;
 	*cainstsvc*)	ns_name=cainstsvc
 			load_dtracepath
+			ns_args="$ns_dbglogfile"
+			;;
+	*castashsvc*)	ns_name=castashsvc
+			stash=$(getprop caconfig/stash-rootdir)
+			[[ -n $stash ]] || fail "no stash configured"
+			echo "using stash '$stash'"
+			ns_args="$stash $ns_dbglogfile"
 			;;
 	*) 		fail "don't know how to start $SMF_FMRI" ;;
 esac
@@ -132,11 +149,8 @@ env | sort | egrep '^(AMQP_|MAPI_|NODE_PATH)' | grep -v PASSWORD
 #
 # Launch the daemon.
 #
-mkdir -p "$ns_logbase/$ns_name" || fail "failed to create log directory"
-ns_dbglogfile="$ns_logbase/$ns_name/amqp-$(date +%F.%T).$$"
-ns_rqlogfile="$ns_logbase/$ns_name/requests-$(date +%F.%T).$$"
 smf_clear_env
-$ns_node $ns_exec $ns_dbglogfile $ns_rqlogfile &
+$ns_node $ns_exec $ns_args &
 ns_pid=$!
 [[ $ns_rt == "true" ]] && run_realtime $ns_pid
 exit $SMF_EXIT_OK
