fix log bugs in canodesvc update versions

diff --git a/smf/method/canodesvc b/smf/method/canodesvc
--- a/smf/method/canodesvc
+++ b/smf/method/canodesvc
@@ -85,6 +85,12 @@ function load_dtracepath
 	echo "DTRACE_LIBPATH=$DTRACE_LIBPATH"
 }
 
+function load_logfiles
+{
+	ns_dbglogfile="$ns_logbase/$ns_name/amqp-$(date +%F.%T).$$"
+	ns_rqlogfile="$ns_logbase/$ns_name/requests-$(date +%F.%T).$$"
+}
+
 function run_realtime
 {
 	local pid=$1
@@ -104,30 +110,27 @@ ns_name=
 ns_args=
 
 #
-# Set up log files and directories
-#
-mkdir -p "$ns_logbase/$ns_name" || fail "failed to create log directory"
-ns_dbglogfile="$ns_logbase/$ns_name/amqp-$(date +%F.%T).$$"
-ns_rqlogfile="$ns_logbase/$ns_name/requests-$(date +%F.%T).$$"
-
-#
 # Figure out which service to start.
 #
 case $SMF_FMRI in
 	*caconfigsvc*)	ns_name=caconfigsvc
+			load_logfiles
 			load_mapi
 			ns_args="$ns_dbglogfile $ns_rqlogfile"
 			;;
 	*caaggsvc*)	export HOST=$(uname -n)-${SMF_FMRI/*:}
 			ns_name=caaggsvc
+			load_logfiles
 			load_geoip
 			ns_args="$ns_dbglogfile"
 			;;
 	*cainstsvc*)	ns_name=cainstsvc
+			load_logfiles
 			load_dtracepath
 			ns_args="$ns_dbglogfile"
 			;;
 	*castashsvc*)	ns_name=castashsvc
+			load_logfiles
 			stash=$(getprop caconfig/stash-rootdir)
 			[[ -n $stash ]] || fail "no stash configured"
 			echo "using stash '$stash'"
@@ -135,6 +138,11 @@ case $SMF_FMRI in
 			;;
 	*) 		fail "don't know how to start $SMF_FMRI" ;;
 esac
+
+#
+# Set up log files and directories
+#
+mkdir -p "$ns_logbase/$ns_name" || fail "failed to create log directory"
 
 cd "$ns_root" || fail "failed to cd"
 ns_root=$(pwd)
