INTRO-560 ca-headnode-setup should invoke sdc-setup -A INTRO-557 proc data cache should translate all possible values. (fix jsstyle)

diff --git a/tools/ca-headnode-setup b/tools/ca-headnode-setup
--- a/tools/ca-headnode-setup
+++ b/tools/ca-headnode-setup
@@ -9,6 +9,7 @@ shopt -s xpg_echo
 
 sh_arg0=$(basename $0)
 sh_tmpbase=/var/tmp/$sh_arg0.$$
+sh_user="$1"
 
 function fail
 {
@@ -18,6 +19,16 @@ function fail
 	exit 1
 }
 
+[[ -n $sh_user ]] || fail "usage: $sh_arg0 <username>"
+
+echo "Marking headnode provisionable ... \c"
+sdc-compnode -c headnode -r false || fail "failed"
+echo "done."
+
+echo "Provisioning cloud services ... \c"
+sdc-setup -c headnode -A || fail "failed"
+echo "done."
+
 [[ -f /lib/sdc/config.sh ]] || fail "Missing /lib/sdc/config.sh"
 
 . /lib/sdc/config.sh
@@ -25,7 +36,6 @@ load_sdc_config
 
 sh_urlbase="${CONFIG_mapi_client_url}"
 sh_capi="${CONFIG_capi_client_url}"
-sh_user="$1"
 sh_mapicurlcmd="curl -u ${CONFIG_mapi_http_admin_user}"
 sh_mapicurlcmd="$sh_mapicurlcmd:${CONFIG_mapi_http_admin_pw}"
 sh_capicurlcmd="curl -u ${CONFIG_capi_http_admin_user}"
@@ -77,29 +87,8 @@ function sh_loadcazone
 
 function sh_load_dataset
 {
-	sh_dataset_version=$($sh_mapicurlcmd -s \
-	    --url $sh_urlbase/search/datasets?name=$sh_dataset_name | \
-	    json 0.version)
-}
-
-function sh_enable_provision
-{
-	local servers length ii entry
-	servers=$($sh_mapicurlcmd -s --url $sh_urlbase/servers)
-	[[ $? -eq 0 ]] || fail "failed to list servers"
-	length=$(echo $servers | json length)
-	entry=""
-	for (( ii=0; ii < length; ii++)) {
-		if echo $servers | json $ii.hostname | \
-		    egrep -s "^$sh_head_hostname$";
-		then
-			entry=$(echo $servers | json $ii.uri)
-		fi	
-	}
-	[[ -z $entry ]] && fail "couldn't find $sh_head_hostname entry"
-	$sh_mapicurlcmd -s -X PUT -F "reserved=false" \
-	    --url $sh_urlbase/admin$entry >/dev/null
-	[[ $? -eq 0 ]] || fail "failed to make $sh_head_hostname provisionable"
+	echo "(using hardcoded) \c"
+	sh_dataset_version=1.3.18	
 }
 
 function sh_provision
@@ -153,8 +142,6 @@ function sh_upload_keys
 	done < $HOME/.ssh/authorized_keys
 }
 
-[[ -n $sh_user ]] || fail "usage: $sh_arg0 <username>"
-
 echo "Retrieving customer uri ... \c"
 sh_loadcust || fail "failed"
 [[ -n $sh_custuri ]] || fail "no customer uri found"
@@ -164,16 +151,12 @@ sh_upload_keys || fail "failed"
 
 echo "Finding CA zone ... \c"
 sh_loadcazone || fail "failed"
-echo "done."
+echo "$sh_cazone."
 
 echo "Finding version of dataset "$sh_dataset_name" ... \c"
 sh_load_dataset || fail "failed"
 [[ -n $sh_dataset_version ]] || fail "no version found"
 echo "$sh_dataset_version"
-
-echo "Marking headnode provisionable ... \c"
-sh_enable_provision || fail "failed"
-echo "done."
 
 echo "Provisioning $sh_dataset_name-$sh_dataset_version zone ... \c"
 sh_provision $sh_cust "$sh_dataset_name-$sh_dataset_version" || fail "failed"
