INTRO-591 move CA to npm 1.0

diff --git a/tools/ca-headnode-setup b/tools/ca-headnode-setup
--- a/tools/ca-headnode-setup
+++ b/tools/ca-headnode-setup
@@ -278,7 +278,7 @@ export PATH=/opt/local/bin:$PATH
 
 echo "Setting up pkgsrc and packages ... \c"
 pkgin update > /var/tmp/pkgin_update.out
-pkgin -y in gcc-compiler gcc-runtime gcc-tools cscope pkg-config gmake scmgit python24 python26 png npm GeoIP GeoLiteCity ghostscript > /var/tmp/pkgin_install.out || fail "failed"
+pkgin -y in gcc-compiler gcc-runtime gcc-tools cscope pkg-config gmake scmgit python24 python26 png npm-1.0.94 GeoIP GeoLiteCity ghostscript > /var/tmp/pkgin_install.out || fail "failed"
 echo "done."
 EOF
 
