INTRO-536 Switch CA builds to use gcc45 by default

diff --git a/tools/ca-headnode-setup b/tools/ca-headnode-setup
--- a/tools/ca-headnode-setup
+++ b/tools/ca-headnode-setup
@@ -260,7 +260,7 @@ tar = gtar
 NPMRC
 
 cat > /home/$sh_user/.profile << PROFILE
-export PATH=/usr/bin:/usr/sbin:/opt/local/bin:/opt/local/sbin:/usr/sfw/bin:/usr/openwin/bin:/usr/ccs/bin:/usr/xpg4/bin:/opt/local/gcc34/bin
+export PATH=/usr/bin:/usr/sbin:/opt/local/bin:/opt/local/sbin:/usr/sfw/bin:/usr/openwin/bin:/usr/ccs/bin:/usr/xpg4/bin
 export MANPATH=/opt/local/man:/opt/local/share/man:/usr/share/man:/usr/sfw/share/man:/usr/openwin/share/man
 PROFILE
 chown -R $sh_user:staff /home/$sh_user || fail "failed to chmod"
@@ -273,7 +273,7 @@ export PATH=/opt/local/bin:$PATH
 
 echo "Setting up pkgsrc and packages ... \c"
 pkgin update > /var/tmp/pkgin_update.out
-pkgin -y in gcc34 gcc-tools cscope pkg-config gmake scmgit python24 python26 png npm GeoIP GeoLiteCity ghostscript > /var/tmp/pkgin_install.out || fail "failed"
+pkgin -y in gcc-compiler gcc-runtime gcc-tools cscope pkg-config gmake scmgit python24 python26 png npm GeoIP GeoLiteCity ghostscript > /var/tmp/pkgin_install.out || fail "failed"
 echo "done."
 EOF
 
