INTRO-650 update ca-headnode-setup for the post-MAPI world AGENT-482 'rm' the service manifest file with the -f argument (fix check)

diff --git a/tools/ca-headnode-setup b/tools/ca-headnode-setup
--- a/tools/ca-headnode-setup
+++ b/tools/ca-headnode-setup
@@ -22,32 +22,55 @@ function sh_extract_header
 
 function sh_provision
 {
-        local cust=$1 dataset=$2
-	local out turi conturi
+	local cust=$1
 
-        out=$($sh_mapicurlcmd -s -i -X POST -d dataset=$dataset \
-	    -d package="regular_256" -d networks="admin" \
-	    -d customer_uuid=$cust \
-	    --url "$sh_mapi/zones" 2>&1)
+	echo "Fetching uuid for $sh_dataset_name $sh_dataset_version ... \c "
+	local dataset_uuid=$(sdc-dsapi \
+	    "/datasets?name=$sh_dataset_name&version=$sh_dataset_version" | \
+	    json -H 0.uuid) || fail "failed"
+	[[ -n $dataset_uuid ]] || fail "not found"
+	echo $dataset_uuid
 
-        [[ $? -eq 0 ]] || fail "failed to create zone: $out"
-	turi=$(echo "$out" | sh_extract_header X-Joyent-Transition-URI)
-	[[ -n $turi ]] || fail "no transition URI: $out"
+	echo "Retrieving admin customer uuid ... \c "
+	local cust_uuid=$(sdc-ldap search cn=Admin | grep uuid: | \
+	    awk '{print $2}') || fail "failed"
+	[[ -n $cust_uuid ]] || fail "not found"
+	echo "$cust_uuid"
 
-	while [[ -z $conturi ]]; do
-		sleep 1
-		out=$($sh_mapicurlcmd -s -i --url $sh_mapi$turi 2>&1)
-        	[[ $? -eq 0 ]] || fail "failed to get transition: $out"
-		conturi=$(echo "$out" | sh_extract_header Location)
-		echo ".\c "
-	done
+	echo "Retrieving admin network uuid ... \c "
+	local net_uuid=$(sdc-napi /networks?name=admin | json -H 0.uuid) || \
+	    fail "failed"
+	[[ -n $net_uuid ]] || fail "not found"
+	echo "$net_uuid"
 
-	out=$($sh_mapicurlcmd $sh_curlopts $sh_mapi$conturi)
-	sh_zonename=$(echo "$out" | json name)
+	echo "Creating dev zone ... \c "
+	sdc-machine create > /var/tmp/casetup.$$.create.log 2>&1 <<-EOF
+	{
+		"brand": "joyent",
+		"dataset_uuid": "$dataset_uuid",
+		"owner_uuid": "$cust_uuid",
+		"networks": [ "$net_uuid" ],
+		"alias": "${sh_user}dev3",
+		"ram": 256,
+		"max_swap": 512,
+		"quota": 10240,
+		"cpu_cap": 100,
+		"max_lwps": 1000,
+		"zfs_io_priority": 10
+	}
+	EOF
+	echo "done."
+
+	echo "Identifying new zone ... \c "
+	sh_zonename=$(sdc-machine list | grep -w "${sh_user}dev3" | \
+	    awk '{print $3}') || fail "failed to fetch machine list"
 	sh_zoneroot=/zones/$sh_zonename/root
-	[[ -n $sh_zonename ]] || fail "no zone name: $out"
-	sh_zoneip=$(echo "$out" | json ips.0.address)
-	[[ -n $sh_zoneip ]] || fail "no zone ip: $out"
+	[[ -n $sh_zonename ]] || fail "zonename not found"
+
+	sh_zoneip=$(sdc-zapi /machines/$sh_zonename | json -H nics.0.ip) || \
+	    fail "failed to fetch IP"
+	[[ -n $sh_zoneip ]] || fail "IP not found"
+	echo "$sh_zonename ($sh_zoneip)"
 }
 
 #
@@ -55,62 +78,39 @@ function sh_provision
 #
 sh_arg0=$(basename $0)			# this script's name
 sh_user="$1"				# desired username
-sh_tmpbase=/var/tmp/$sh_arg0.$$		# temporary directory
 sh_dataset_name=smartos			# dataset name to provision
 sh_dataset_version=1.6.3		# desired version to provision
 sh_zonename=				# provisioned zone's uuid
 sh_zoneip=				# provisioned zone's IP
 sh_zoneroot=				# provisioned zone's /
-sh_zones="moray ufds ca adminui redis amon cloudapi portal"
-
-sh_capi=				# CAPI client URL base
-sh_capicurlcmd=				# curl command to call CAPI
-sh_mapi=				# MAPI client URL base
-sh_mapicurlcmd=				# curl command to call MAPI
 sh_cust=				# admin user's customer uuid
-sh_curlopts="-H 'Accept: application/json' -s"	# common curl options
+sh_zones="ca adminui redis amon cloudapi portal"
 
 [[ -n $sh_user ]] || fail "usage: $sh_arg0 <username>"
 
 #
 # The basic sequence of operations is as follows:
 #
-# - mark headnode provisionable
-# - use sdc-setup to set up common zones (requires provisionable headnode)
-# - load SDC configuration (which isn't complete until we've run sdc-setup)
+# - use sdc-role to set up common zones (requires provisionable headnode)
 # - provision the development zone and wait for it to boot
 # - setup the zone (create user and install packages)
 #
-echo "Marking headnode provisionable ... \c "
-sdc-compnode -c headnode -r false || fail "failed"
+echo "Listing existing SDC zones ... \c "
+sdc-role list | awk '{print $6}' > /var/tmp/casetup.$$.zones || fail "failed"
 echo "done."
 
-echo "Provisioning cloud services ... \c "
-sdc-setup -c headnode -r $sh_zones || fail "failed"
-echo "done."
+for zone in $sh_zones; do
+	if grep -w $zone /var/tmp/casetup.$$.zones > /dev/null; then
+		echo "Skipping zone $zone (already exists)."
+		continue
+	fi
 
-echo "Loading SDC configuration ... \c "
-[[ -f /lib/sdc/config.sh ]] || fail "Missing /lib/sdc/config.sh"
-. /lib/sdc/config.sh
-load_sdc_config
+	echo "Provisioning zone $zone ... \c "
+	sdc-role create $zone > /var/tmp/casetup-$$-$zone.log || fail "failed"
+	echo "done."
+done
 
-sh_capi="${CONFIG_capi_client_url}"
-sh_capicurlcmd="curl -u ${CONFIG_capi_http_admin_user}"
-sh_capicurlcmd="$sh_capicurlcmd:${CONFIG_capi_http_admin_pw}"
-
-sh_mapi="${CONFIG_mapi_client_url}"
-sh_mapicurlcmd="curl -u ${CONFIG_mapi_http_admin_user}"
-sh_mapicurlcmd="$sh_mapicurlcmd:${CONFIG_mapi_http_admin_pw}"
-echo "done."
-
-echo "Retrieving admin customer uuid ... \c "
-sh_cust=$($sh_capicurlcmd $sh_curlopts $sh_capi/customers | json 0.uuid)
-[[ -n $sh_cust ]] || fail "not found"
-echo "$sh_cust"
-
-echo "Provisioning $sh_dataset_name-$sh_dataset_version zone ... \c "
-sh_provision $sh_cust "$sh_dataset_name-$sh_dataset_version" || fail "failed"
-echo "$sh_zonename ($sh_zoneip)"
+sh_provision $sh_cust
 
 #
 # Work around PROV-487.  The zone may be booted, but it might be running
