INTRO-629 catest could emit TAP output

diff --git a/tools/catest b/tools/catest
--- a/tools/catest
+++ b/tools/catest
@@ -1,369 +1,336 @@
 #!/usr/bin/bash
 
 #
-# catest: a tool and framework for testing cloud analytics.
-#
-
-#
-# Test name format:
-# Tests can be in any language and should be of the format
-# tst.<testname>.<language ext>. Language extension tells us which interpreter
-# we will end up firing up to test this, i.e. shell, node, etc. Tests can be in
-# an arbitrary directory hierarchy 
-#
-
-#
-# Per test actions:
-# - Make a directory for that test
-# - cd into that directory and exec the test
-# - Redirect standard output and standard error to files
-# - Tests return 0 to indicate success, non-zero to indicate failure
+# catest: a simple testing tool and framework. See usage below for details.
 #
 
 shopt -s xpg_echo
 
 #
-# Canoncial name
+# Global configuration
 #
-PNAME=$(basename $0)
+cat_arg0=$(basename $0)			# canonical name of "catest"
+cat_outbase="catest.$$"			# output directory name
+cat_tstdir="tst"			# top-level test directory
+cat_node="deps/node/node"		# relative path to "node"
 
 #
-# Should we keep the output of successful tests?
+# Options and arguments
 #
-OPT_KEEP_SUCCESS=0
+cat_tests=""				# list of tests (absolute paths)
+opt_a=false				# run all tests
+opt_k=false				# keep output of successful tests
+opt_o="/var/tmp"			# containing directory for output directory
+opt_t=					# TAP format output file
 
 #
-# Should we run all tests
+# Current state
 #
-OPT_RUN_ALL=0
+cat_outdir=				# absolute path to output directory
+cat_tapfile=				# absolute path of TAP output file
+cat_ntests=				# total number of tests
+cat_nfailed=0				# number of failed tests run
+cat_npassed=0				# number of successful tests run
+cat_nrun=0				# total number of tests run
 
 #
-# Output directory
+# fail MSG: emits the given error message to stderr and exits non-zero.
 #
-OPT_OUTPUT_DIR=""
-
-#
-# Name for our results directory
-#
-OUTPUT_DIR_NAME="catest.$$"
-
-#
-# Name of the top level directory containts tests
-#
-TST_DIR_NAME="tst"
-
-#
-# Tests that ran, but failed
-#
-CURRENT_FAILURES=0
-
-#
-# Tests that passed
-#
-CURRENT_PASSES=0
-
-#
-# Total number of tests run
-#
-TESTS_RUN=0
-
-#
-# Number of tests skipped
-#
-TESTS_SKIPPED=0
-
-#
-# node relative path
-#
-NODE_REL="deps/node/node"
-
-#
-# Absolute path to the node executable
-# This is exported to the environment
-#
-NODE_EXEC=""
-
-#
-# Absolute path to the bash executable
-#
-BASH_EXEC="/usr/bin/bash"
-
-#
-# Populated via input arguments, is an absolute path
-#
-OUTPUT_BASE_DIR=""
-
-#
-# Temporary directory for tests to use
-#
-CATMPDIR="/var/tmp/catest.$$_tmpfiles"
-export CATMPDIR
-
-#
-# Populated via setup-output, is an absolute path
-#
-OUTPUT_DIR=""
-
-#
-# Populated via get-tests, is a series of absolute paths
-#
-TESTS=""
-
-#
-# Make sure that we use a different AMQP Namespace
-#
-CA_AMQP_PREFIX="test"
-export CA_AMQP_PREFIX
-
-#
-# Keep track of the hostname and export that env variable for these tests as a
-# fallback for those who don't set it themselves.
-#
-HOSTNAME=$(/usr/bin/hostname)
-export HOST=$HOSTNAME
-
 function fail
 {
-	echo "$@" >&2
+	echo "$cat_arg0: $@" >&2
+
+	[[ -n $cat_tapfile ]] && echo "Bail out! $@" >> $cat_tapfile
+
 	exit 1
 }
 
+#
+# usage [MSG]: emits the given message, if any, and a usage message, then exits.
+#
 function usage
 {
-	if [[ $# -ne 0 ]]; then
-		echo "$PNAME: $@"
-	fi
+	[[ $# -ne 0 ]] && echo "$cat_arg0: $@\n" >&2
+
 	cat <<USAGE >&2
-Usage: $PNAME -o dir [opts] tests
+Usage: $cat_arg0 [-k] [-o dir] [-t file] test1 ...
+       $cat_arg0 [-k] [-o dir] [-t file] -a
 
-Runs specified tests for cloud analytics.
+In the first form, runs specified tests.  In the second form, runs all tests
+found under "$cat_tstdir" of the form "tst*.<ext>" for supported extensions.
 
-	-o directory	Specifies the output directory for tests
-	-a 		Runs all tests, ignores tests passed in
+TESTS
+
+    Tests are just files to be executed by some interpreter. In most cases, a
+    test succeeds if it exits successfully and fails otherwise.  You can also
+    specify the expected stdout of the test in a file with the same name as the
+    test plus a ".out" suffix, in which case the test will also fail if the
+    actual output does not match the expected output.
+
+    Supported interpreter extensions are "sh" (bash) and "js" (node).
+
+    This framework does not provide per-test setup/teardown facilities, but
+    test files can do whatever they want, including making use of common
+    libraries for setup and teardown.
+
+TEST OUTPUT
+
+    Summary output is printed to stdout.  TAP output can be emitted with "-t".
+
+    Per-test output is placed in a new temporary directory inside the directory
+    specified by the -o option, or /var/tmp if -o is not specified.
+    
+    Within the output directory will be a directory for each failed test which
+    includes a README describing why the test failed (e.g., exited non-zero), a
+    copy of the test file itself, the actual stdout and stderr of the test, and
+    the expected stdout of the test (if specified).
+    
+    If -k is specified, the output directory will also include a directory for
+    each test that passed including the stdout and stderr from the test.
+
+The following options may be specified:
+
+	-a 		Runs all tests under $cat_tstdir
+			(ignores other arguments)
 	-h		Output this message
 	-k		Keep output from all tests, not just failures
+	-o directory	Specifies the output directory for tests
+			(default: /var/tmp)
+	-t file		Emit summary output in TAP format
 
 USAGE
+
 	exit 2
 }
 
-
-function setup
+#
+# abspath FILE: emits a canonical, absolute path to the given file or directory.
+#
+function abspath
 {
-	base=$1
-	pushd "$base/../" >/dev/null
-	export SRC=$(pwd)
-	if [[ ! -f $NODE_REL || ! -x $NODE_REL ]]; then
-		fail "Node executable not at deps/node/node"
-	fi
-	NODE_EXEC="$(pwd)/$NODE_REL"
-	export NODE_EXEC=$NODE_EXEC
-	popd >/dev/null
-	pushd $base >/dev/null
-	export $(./npath)
-	export PATH=$(pwd)/../deps/ctf2json:$PATH
-	popd >/dev/null
-	if [[ ! -f $BASH_EXEC || ! -x $BASH_EXEC ]]; then
-		fail "Missing bash executable at $BASH"
+	local dir=$(dirname $1) base=$(basename $1)
+
+	if [[ $base = ".." ]]; then
+		cd "$dir"/.. > /dev/null || fail "abspath '$1': failed to chdir"
+		pwd
+		cd - > /dev/null || fail "abspath '$1': failed to chdir back"
+	else
+		cd "$dir" || fail "abspath '$1': failed to chdir"
+		echo "$(pwd)/$base"
+		cd - > /dev/null || fail "abspath '$1': failed to chdir back"
 	fi
 }
 
-function check-amqp
-{
-	[[ -z "$AMQP_HOST" ]] && fail "AMQP_HOST not set"
-	unset MACHINE_THAT_GOES_PING
-	echo "Checking for AMQP_HOST... \c "
-	ping "$AMQP_HOST" 2 >/dev/null ||
-	    fail "couldn't reach AMQP_HOST: $AMQP_HOST"
-	echo "done"
-}
-
-function get-output-base
-{
-	pushd $1 >/dev/null
-	OUTPUT_BASE_DIR=$(pwd)
-	popd >/dev/null
-}
-
 #
-# Finds all of the tests that we are going to run
+# cleanup_test TESTDIR "success" | "failure": cleans up the output directory
+#     for this test
 #
-function get-all-tests
+function cleanup_test
 {
-	base=$1
-	tst_root="$base/../$TST_DIR_NAME"
-	[[ -d $tst_root ]] || fail "Cannot find test directory"
-	pushd $tst_root >/dev/null
-	tst_root=$(pwd)
-	popd >/dev/null
-	TESTS=$(find $tst_root -name 'tst*.js' -o -name 'tst*.sh')
-	[[ "TESTS" != "" ]] || fail "Found no tests to run"
-}
+	local test_odir="$1" result=$2
+	local newdir
 
-function welcome
-{
-	NUM_TESTS=$(echo $TESTS | wc -w)
-	printf "Welcome to catest\n"
-	printf "Configuration:\n"
-	printf "\tOutput Directory: $OUTPUT_BASE_DIR/$OUTPUT_DIR_NAME\n"
-	printf "\tTemp Directory: $CATMPDIR\n"
-	printf "\tNode executable: $NODE_EXEC\n"
-	printf "\tKeep non-failure output: $OPT_KEEP_SUCCESS\n"
-	printf "\tFound %d test(s) to run\n" $NUM_TESTS
+	if [[ $result = "success" ]]; then
+		newdir="$(dirname $test_odir)/success.$cat_npassed"
+	else
+		newdir="$(dirname $test_odir)/failure.$cat_nfailed"
+	fi
+
+	mv "$test_odir" "$newdir"
+	echo $newdir
 }
 
 #
-# Make our output directory
+# emit_failure TEST ODIR REASON: indicate that a test has failed
 #
-function setup-output
+function emit_failure
 {
-	pushd $OUTPUT_BASE_DIR >/dev/null
-	mkdir $OUTPUT_DIR_NAME || fail "Can't make output directory"
-	cd $OUTPUT_DIR_NAME
-	OUTPUT_DIR=$(pwd)
-	popd >/dev/null
+	local test_label=$1 odir=$2 reason=$3
 
-	mkdir -p $CATMPDIR || fail "Can't make temp directory"
+	if [[ $cat_tapfile ]]; then
+		echo "not ok $(($cat_nrun+1)) $test_label" >> $cat_tapfile
+	fi
+
+	echo "FAILED."
+	echo "$test_path failed: $reason" > "$odir/README"
+
+	[[ -n "$odir" ]] && echo ">>> failure details in $odir\n"
+	((cat_nfailed++))
+}
+
+#
+# emit_pass TEST: indicate that a test has passed
+#
+function emit_pass
+{
+	local test_label=$1
+
+	if [[ $cat_tapfile ]]; then
+		echo "ok $((cat_nrun+1)) $test_label" >> $cat_tapfile
+	fi
+
+	echo "success."
+	((cat_npassed++))
 }
 
 #
 # Executes a single test
 #
-function execute-test
+# Per-test actions:
+# - Make a directory for that test
+# - cd into that directory and exec the test
+# - Redirect standard output and standard error to files
+# - Tests return 0 to indicate success, non-zero to indicate failure
+#
+function execute_test
 {
 	[[ $# -eq 1 ]] || fail "Missing test to execute"
-	test_path=$1
-	test_name=$(basename $1)
-	test_label=$(echo $test_path | sed -e s#^$SRC/##)
-	test_dir=$(dirname $1)
-	test_odir="$OUTPUT_DIR/test.$TESTS_RUN"
-	ext=${test_name##*.}
-	reason=
-	EXEC=""
+	local test_path=$1
+	local test_name=$(basename $1)
+	local test_dir=$(dirname $1)
+	local test_label=$(echo $test_path | sed -e s#^$SRC/##)
+	local test_odir="$cat_outdir/test.$cat_nrun"
+	local ext=${test_name##*.}
+	local faildir
+	local EXEC
+
+	echo "Executing test $test_label ... \c "
+	mkdir "$test_odir" >/dev/null || fail "failed to create test directory"
+	cp "$test_path" "$test_odir"
 
 	case "$ext" in
 	"sh") 	EXEC=$BASH_EXEC	;;
 	"js") 	EXEC=$NODE_EXEC ;;
-	*) 	echo "Skipping test $test_label (unknown type)"
-		((TESTS_SKIPPED++))
+	*) 	faildir=$(cleanup_test "$test_odir" "failure")
+		emit_failure "$test_label" "$faildir" "unknown file extension"
 		return 0
 		;;
 	esac
 
-	echo "Executing test $test_label ... \c"
-
-	mkdir "$test_odir" >/dev/null || fail "Can't make directory"
 	pushd "$test_dir" >/dev/null
 	$EXEC $test_name >$test_odir/$$.out 2>$test_odir/$$.err
 	execres=$?
 	popd > /dev/null
 
 	if [[ $execres != 0 ]]; then
-		reason="test returned $execres instead of 0"
-	elif [[ -f $test_path.out ]] && \
+		faildir=$(cleanup_test "$test_odir" "failure")
+		emit_failure "$test_label" "$faildir" "test returned $execres"
+		return 0
+	fi
+
+	if [[ -f $test_path.out ]] && \
 	    ! diff $test_path.out $test_odir/$$.out > /dev/null ; then
 		cp $test_path.out $test_odir/$test_name.out
-		reason="stdout mismatch"
+		faildir=$(cleanup_test "$test_odir" "failure")
+		emit_failure "$test_label" "$faildir" "stdout mismatch"
+		return 0
 	fi
 
-	if [[ -z $reason ]]; then
-		echo "success."
-		mv "$test_odir" "$OUTPUT_DIR/success.$CURRENT_PASSES"
-		((CURRENT_PASSES++))
-		return;
-	fi
-
-	echo "FAILED."
-	echo "$test_path failed: $reason" > "$test_odir/README"
-	printf ">>> failure details in %s/failure.%d\n\n" \
-	    $OUTPUT_DIR $CURRENT_FAILURES
-	cp "$test_path" "$test_odir/$test_name"
-	mv "$test_odir" "$OUTPUT_DIR/failure.$CURRENT_FAILURES"
-	((CURRENT_FAILURES++))
+	cleanup_test "$test_odir" "success" > /dev/null
+	emit_pass "$test_label"
 }
 
-#
-# Print out final numbers
-#
-function results
-{
-	printf "\n===================================================\n\n"
-	printf "Results:\n"
-	printf "\tTests passed:\t%2d/%2d\n" $CURRENT_PASSES $TESTS_RUN
-	printf "\tTests failed:\t%2d/%2d\n" $CURRENT_FAILURES $TESTS_RUN
-	printf "\tTests skipped:\t%2d/%2d\n" $TESTS_SKIPPED $TESTS_RUN
-	printf "\n===================================================\n"
-}
-
-function cleanup
-{
-	if [ $OPT_KEEP_SUCCESS -eq 0 ]; then
-		pushd $OUTPUT_DIR >/dev/null
-		rm -rf success.*
-		rm -rf error.*
-		popd >/dev/null
-	fi
-}
-
-base=$(dirname $0)
-
-while getopts ":o:akh" c $@; do
+while getopts ":o:t:akh?" c $@; do
 	case "$c" in
-	a) 
-		OPT_RUN_ALL=1
-		;;
-	k)
-		OPT_KEEP_SUCCESS=1
-		;;
-	o)
-		OPT_OUTPUT_DIR=$OPTARG	
-		;;
-	h)
-		usage
-		;;
-	:)
-		usage "option requires an argument -- $OPTARG"
-		;;
-	*)
-		usage "invalid option: $OPTARG"
-		;;
+	a|k) 	eval opt_$c=true ;;
+	o|t) 	eval opt_$c="$OPTARG" ;;
+	h)	usage ;;
+	:) 	usage "option requires an argument -- $OPTARG" ;;
+	*) 	usage "invalid option: $OPTARG" ;;
 	esac
 done
 
 shift $((OPTIND-1))
+[[ $# -eq 0 && $opt_a == "false" ]] && \
+    usage "must specify \"-a\" or list of tests"
 
-if [ "$OPT_OUTPUT_DIR" == "" ]; then
-	OPT_OUTPUT_DIR="/var/tmp"
-fi
+#
+# Initialize paths and other environment variables.
+#
+export SRC=$(abspath $(dirname $0)/..)
+export PATH=$SRC/deps/ctf2json:$PATH
+export NODE_EXEC=$(abspath $SRC/$cat_node)
+export BASH_EXEC="/usr/bin/bash"
+export $($SRC/tools/npath)
+[[ -n $HOST ]] || export HOST=$(hostname)
 
-if [ $# -eq 0 -a $OPT_RUN_ALL -eq 0 ]; then
-	usage "must specify tests to run or -a"
-fi
+[[ -x $NODE_EXEC ]] || fail "executable node not found at $NODE_EXEC"
+[[ -x $BASH_EXEC ]] || fail "executable bash not found at $BASH_EXEC"
 
-setup $base
-get-output-base $OPT_OUTPUT_DIR
+#
+# We create and set CATMPDIR as a place for the tests to store temporary files.
+#
+export CATMPDIR="/var/tmp/catest.$$_tmpfiles"
 
-if [ $OPT_RUN_ALL -eq 1 ]; then
-	get-all-tests $base
+#
+# We set an AMQP prefix to avoid conflicting with an existing CA deployment.
+#
+export CA_AMQP_PREFIX="test"
+
+if [[ $opt_a = "true" ]]; then
+	cat_tests=$(find $SRC/$cat_tstdir -name 'tst*.js' -o -name 'tst*.sh') || \
+	    fail "failed to locate tests in $SRC/$cat_tstdir"
 else
 	for t in $@; do
 		[[ -f $t ]] || fail "cannot find test $t"
-		pushd $(dirname $t) >/dev/null
-		abs=$(pwd)
-		popd >/dev/null
-		TESTS="$abs/$(basename $t) $TESTS"
+		cat_tests="$(abspath $t) $cat_tests"
 	done
 fi
 
-welcome
-check-amqp
-printf "\n===================================================\n\n"
-setup-output
+mkdir -p "$opt_o/$cat_outbase"
+cat_outdir=$(abspath $opt_o/$cat_outbase)
 
-for t in $(echo $TESTS | sort); do
-	execute-test $t
-	((TESTS_RUN++))
+mkdir -p $CATMPDIR || fail "failed to create $CATMPDIR"
+
+cat_ntests=$(echo $cat_tests | wc -w)
+printf "Configuration:\n"
+printf "    SRC:                         $SRC\n"
+printf "    AMQP_HOST:                   $AMQP_HOST\n"
+printf "    Output directory:            $cat_outdir\n"
+printf "    Temp directory:              $CATMPDIR\n"
+if [[ -n "$opt_t" ]]; then
+    cat_tapfile=$(abspath $opt_t)
+    printf "    TAP output:                  $cat_tapfile\n"
+fi
+printf "    Keep successful test output: $opt_k\n"
+printf "    Found %d test(s) to run\n\n" $cat_ntests
+
+#
+# Validate parameters and finish setup.
+#
+[[ $cat_ntests -gt 0 ]] || fail "no tests found"
+
+[[ -n "$AMQP_HOST" ]] || fail "AMQP_HOST not set"
+echo "Checking AMQP_HOST ... \c "
+unset MACHINE_THAT_GOES_PING
+ping "$AMQP_HOST" 2 >/dev/null || fail "couldn't reach AMQP_HOST: $AMQP_HOST"
+echo "done"
+
+if [[ -n "$cat_tapfile" ]]; then
+	echo "1..$(($cat_ntests))" > $cat_tapfile || fail "failed to emit TAP output"
+fi
+
+#
+# Start the test run.
+#
+printf "===================================================\n\n"
+
+for t in $(echo $cat_tests | sort); do
+	execute_test $t
+	((cat_nrun++))
 done
-results
-cleanup
-exit $CURRENT_FAILURES
+
+printf "\n===================================================\n\n"
+printf "Results:\n"
+printf "\tTests passed:\t%2d/%2d\n" $cat_npassed $cat_nrun
+printf "\tTests failed:\t%2d/%2d\n" $cat_nfailed $cat_nrun
+printf "\n===================================================\n"
+
+if [[ $opt_k == "false" ]]; then
+	echo "Cleaning up output from successful tests ... \c "
+	rm -rf $cat_outdir/success.*
+	rm -rf $CATMPDIR
+	echo "done."
+fi
+
+exit $cat_nfailed
