INTRO-690 dev user should have Primary Administrator profile

diff --git a/tools/devsetup b/tools/devsetup
--- a/tools/devsetup
+++ b/tools/devsetup
@@ -166,7 +166,8 @@ function setup_devzone
 		echo "skipped (already exists)"
 	else
 	useradd -c $sh_user -d /home/$sh_user -G staff -s /bin/bash \
-	    -K defaultpriv="$sh_privs" $sh_user || fail "failed to create user"
+	    -P "Primary Administrator" -K defaultpriv="$sh_privs" \
+	    $sh_user || fail "failed to create user"
 	passwd -N $sh_user > /dev/null || fail "passwd -N failed for $sh_user"
 	chown -R $sh_user:staff /home/$sh_user || fail "failed to chmod"
 	echo "done."
